### ISSUE TITLE
Skip check for local pacakges

### ISSUE THREAD

**Issue by atsyplenkov** [wurli/updateme#13]
Hi, Jacob 👋!

Consider to skip checking for local packages (i.e., unpublished); otherwise, `updateme` will throw an error, and the package will not be loaded.
> Error in if (inform_if_ahead) "ahead": the argument is of length zero.

**Comment by wurli** [comment]
Hi! Thanks for the suggestion. A few thoughts about this:
* The error you're getting should definitely be fixed - I'll look into this
* I might need to think more about how to handle local packages:
  * If you're loading from `.Rprofile` and finding it annoying, `updateme_off()` should be a pretty quick fix
  * In my workplace, many of our analytical projects are structured as packages. People working in this way might like to have {updateme} available.
* {renv} projects might present a similar problem

Maybe we need something like an ability to turn {updateme} off by creating a special file in the working directory, e.g. `_disable_updateme`

**Comment by atsyplenkov** [comment]
Oof, I am afraid I am not a target user in such a case. I use a maximum of 1-2 local packages in my workflow, and I try to publish them on GitHub as soon as possible. So, I would prefer to have an option like `updateme_local_off()` which can possibly be run from the `.Rprofile`. Otherwise, every R script should have a strange package import like below, am I right?
```
library(updateme)
library(tidyverse)
# other CRAN/GH/Bio packages
updateme_off()
library(LOCAL)
updateme_on() # in case you would have to load packages afterwards
```

**Comment by wurli** [comment]
Ah, thanks for clarification, I think I understand your use-case better now. I think you should be able to get your intended behaviour using `updateme_sources_set()`?

E.g, if you're working on local packages {foo} and {bar} you can use:
``` r
updateme_sources_set(foo = NA, bar = NA)
```

**Comment by wurli** [comment]
The error you raised _should_ also now be fixed - grateful if you could confirm :) 

> `updateme` will throw an error, and the package will not be loaded.
> 
> > Error in if (inform_if_ahead) "ahead": the argument is of length zero.

**Comment by atsyplenkov** [comment]
All good! Thanks!
